name: tests
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19.1'
      - name: download dependencies
        run: |
          go mod download
      - name: run tests
        run: |
          go test .
      - name: run tests with coverage
        id: coverage_test
        run: |
          go test . -cover | grep -Eo "coverage:\ [[:digit:]]{1,3}\.[[:digit:]]{1,3}\%" >> $GITHUB_OUTPUT
      - name: generate coverage badge
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: coverage
          LABEL: 'coverage'
          STATUS: ${{ join(steps.run_tests.outputs.*, '') }}
          COLOR: 00EEFF
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: run bench tests
        run: |
          go test -bench=. -benchmem


